// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk0h2TTa343BKgz3jDrbj9dmF5pStv6v8',
    appId: '1:622716077511:web:04f579b3718b2866fa85e2',
    messagingSenderId: '622716077511',
    projectId: 'buzee-backend',
    authDomain: 'buzee-backend.firebaseapp.com',
    storageBucket: 'buzee-backend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmNci59zI0pO9zzknwU9V_EZgs6r8vFHY',
    appId: '1:622716077511:android:08a24bfdf3da9800fa85e2',
    messagingSenderId: '622716077511',
    projectId: 'buzee-backend',
    storageBucket: 'buzee-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5vpPvuZWAJQPmcM3lQm_nyrsrvLD8mJ0',
    appId: '1:622716077511:ios:2f3e2da351bd799efa85e2',
    messagingSenderId: '622716077511',
    projectId: 'buzee-backend',
    storageBucket: 'buzee-backend.appspot.com',
    iosClientId: '622716077511-sfvemdo4r3ie3neecngbom73ccg97tro.apps.googleusercontent.com',
    iosBundleId: 'com.example.buzee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5vpPvuZWAJQPmcM3lQm_nyrsrvLD8mJ0',
    appId: '1:622716077511:ios:2f3e2da351bd799efa85e2',
    messagingSenderId: '622716077511',
    projectId: 'buzee-backend',
    storageBucket: 'buzee-backend.appspot.com',
    iosClientId: '622716077511-sfvemdo4r3ie3neecngbom73ccg97tro.apps.googleusercontent.com',
    iosBundleId: 'com.example.buzee',
  );
}
